name: Autoupdate
on:
  [push]
jobs:
  pre-commit:
    name: Pre-commit
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: Eijebong/gha-releng-test/pre-commit-autoupdate@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
