name: Autoupdate
on: [push]
jobs:
  pre-commit:
    name: Pre-commit
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
      - name: Setup git
        run: |
          git config --global user.name "Pre-commit automation"
          git config --global user.email "eijebong@bananium.fr"
      - name: Update files
        run: |
          git checkout -B pre-commit-update
          echo "test" > foo
          git add foo
          git commit -am "WIP"
          git push -f origin pre-commit-update
      - name: Create PR if necessary
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos${{ github.reository_owner }}/${{ github.repository }}/pulls \
          -d '{"title":"Update pre-commit","body":"","head":"pre-commit-update","base":"${{ github.event.repository.default_branch }}"}'
