name: Pre-commit
on:
  push:
  pull_request:
  pull_request_review:
    types: [submitted]

jobs:
  pre-commit:
    if: (github.event.review.state == 'approved' && github.event.pull_request.head == 'pre-commit-udpate') || github.event.pull_request.head != 'pre-commit-udpate'
    name: Pre-commit
    runs-on: ubuntu-latest
    steps:
      - uses: Eijebong/gha-releng-test/pre-commit@main
