name: Pre-commit
on:
  push:
  pull_request:
  pull_request_review:
    types: [submitted]

jobs:
  pre-commit:
    # Run the workflow on approval for auto updates only and on push on every other PR
    if: (github.event.review.state == 'approved' && github.event.pull_request.head.ref == 'pre-commit-update') ||
        (github.event.type != 'pull_request_review' && github.event.pull_request.head.ref != 'pre-commit-update')
    name: Pre-commit
    runs-on: ubuntu-latest
    steps:
      - uses: Eijebong/gha-releng-test/pre-commit@main
