name: Pre-commit
on:
  push:
  pull_request:
  pull_request_review:
    types: [submitted]

jobs:
  pre-commit:
    name: Pre-commit
    runs-on: ubuntu-latest
    steps:
      - uses: Eijebong/gha-releng-test/pre-commit@main
